def spot_jsonptojson(jsonstr):
    jsonstr = jsonstr[ jsonstr.index("(") + 1 : jsonstr.rindex(")") ]
    jsonstr = jsonstr.replace('\\n', '').replace('\\r', '')
    jsonstr = jsonstr.replace('vers:','"vers":')
    jsonstr = jsonstr.replace('0.01,','"0.01",')
    jsonstr = jsonstr.replace('name:"db.','size:"db.')
    jsonstr = jsonstr.replace('"USD"','USD')
    jsonstr = jsonstr.replace('USD','"USD"')
    jsonstr = jsonstr.replace('tiers','"tiers"')
    jsonstr = jsonstr.replace('types:','"types":')
    jsonstr = jsonstr.replace('type:','"type":')
    jsonstr = jsonstr.replace('ECU:','"ECU":')
    jsonstr = jsonstr.replace('vCPU:','"vCPU":')
    jsonstr = jsonstr.replace('memoryGiB:','"memoryGiB":')
    jsonstr = jsonstr.replace('storageGB:','"storageGB":')
    jsonstr = jsonstr.replace('tiers:','"tiers":')
    jsonstr = jsonstr.replace('generation:','"generation":')
    jsonstr = jsonstr.replace('yearTerm','yrTerm')
    jsonstr = jsonstr.replace('multiAZ','Multi-AZ')
    jsonstr = jsonstr.replace('us-west-2','us-wes2t')
    jsonstr = jsonstr.replace('us-west-1','us-wes1t')
    jsonstr = jsonstr.replace('us-west','us-west-1')
    jsonstr = jsonstr.replace('us-wes1t','us-west-1')
    jsonstr = jsonstr.replace('us-wes2t','us-west-2')
    jsonstr = jsonstr.replace('us-east-1','us-east')
    jsonstr = jsonstr.replace('us-east','us-east-1')

    return(jsonstr)

def demand_jsonptojson(jsonstr):
    jsonstr = jsonstr[ jsonstr.index("(") + 1 : jsonstr.rindex(")") ]
    jsonstr = jsonstr.replace('\\n', '').replace('\\r', '')
    jsonstr = jsonstr.replace('vers:','"vers":')
    jsonstr = jsonstr.replace('0.01,','"0.01",')
    jsonstr = jsonstr.replace('config','"config"')
    jsonstr = jsonstr.replace('regions:','"regions":')
    jsonstr = jsonstr.replace('region:','"region":')
    jsonstr = jsonstr.replace('instanceTypes','"instanceTypes"')
    jsonstr = jsonstr.replace('prices','"prices"')
    jsonstr = jsonstr.replace('name:"db.','size:"db.')
    jsonstr = jsonstr.replace('name','"name"')
    jsonstr = jsonstr.replace('"USD"','USD')
    jsonstr = jsonstr.replace('USD','"USD"')
    jsonstr = jsonstr.replace('rate','"rate"')
    jsonstr = jsonstr.replace('valueColumns','"valueColumns"')
    jsonstr = jsonstr.replace('sizes:','"sizes":')
    jsonstr = jsonstr.replace('size:','"size":')
    jsonstr = jsonstr.replace('tiers','"tiers"')
    jsonstr = jsonstr.replace('currencies','"currencies"')
    jsonstr = jsonstr.replace('types:','"types":')
    jsonstr = jsonstr.replace('type:','"type":')
    jsonstr = jsonstr.replace('ECU:','"ECU":')
    jsonstr = jsonstr.replace('vCPU:','"vCPU":')
    jsonstr = jsonstr.replace('memoryGiB:','"memoryGiB":')
    jsonstr = jsonstr.replace('storageGB:','"storageGB":')
    jsonstr = jsonstr.replace('tiers:','"tiers":')
    jsonstr = jsonstr.replace('generation:','"generation":')
    jsonstr = jsonstr.replace('yearTerm','yrTerm')
    jsonstr = jsonstr.replace('multiAZ','Multi-AZ')
    jsonstr = jsonstr.replace('us-west-2','us-wes2t')
    jsonstr = jsonstr.replace('us-west-1','us-wes1t')
    jsonstr = jsonstr.replace('us-west','us-west-1')
    jsonstr = jsonstr.replace('us-wes1t','us-west-1')
    jsonstr = jsonstr.replace('us-wes2t','us-west-2')
    jsonstr = jsonstr.replace('us-east-1','us-east')
    jsonstr = jsonstr.replace('us-east','us-east-1')

    return(jsonstr)
